/**
 * Mock Teams Data
 *
 * This file contains realistic mock team data for development and testing.
 * Each team includes proper references and realistic information.
 */

import type { Doc } from "../../../convex/_generated/dataModel";

/**
 * Mock team data that matches the Convex teams schema
 *
 * Note: In real data, _id would be generated by Convex.
 * For mock data, we use string IDs for consistency.
 */
export const mockTeams: Doc<"teams">[] = [
	{
		_id: "team_1" as any,
		_creationTime: Date.now() - 86400000 * 30, // 30 days ago
		tournamentId: "tournament_1" as any,
		name: "Thunderbirds",
		description: "Competitive youth baseball team with strong batting lineup",
		coachName: "Michael Rodriguez",
		coachEmail: "m.rodriguez@thunderbirds.com",
		coachPhone: "555-0123",
		city: "Springfield",
		homeField: "Riverside Park",
		organization: "Springfield Youth Baseball League",
		teamAgeGroup: "U14",
		status: "active",
		captainPlayerId: "player_3" as any,
		createdAt: Date.now() - 86400000 * 30, // 30 days ago
		updatedAt: Date.now() - 86400000 * 2, // 2 days ago
	},
	{
		_id: "team_2" as any,
		_creationTime: Date.now() - 86400000 * 25,
		tournamentId: "tournament_1" as any,
		name: "Warriors",
		description: "Focused on defensive strategy and teamwork",
		coachName: "Sarah Johnson",
		coachEmail: "s.johnson@warriors.com",
		coachPhone: "555-0124",
		city: "Riverside",
		homeField: "Central Stadium",
		organization: "Riverside Athletic Association",
		teamAgeGroup: "U14",
		status: "active",
		captainPlayerId: "player_7" as any,
		createdAt: Date.now() - 86400000 * 25,
		updatedAt: Date.now() - 86400000 * 5,
	},
	{
		_id: "team_3" as any,
		_creationTime: Date.now() - 86400000 * 20,
		tournamentId: "tournament_1" as any,
		name: "Eagles",
		description: "Fast-paced team with excellent base running skills",
		coachName: "David Chen",
		coachEmail: "d.chen@eagles.com",
		coachPhone: "555-0125",
		city: "Oakland",
		homeField: "Eagles Field",
		organization: "Oakland Sports Club",
		teamAgeGroup: "U14",
		status: "active",
		captainPlayerId: "player_12" as any,
		createdAt: Date.now() - 86400000 * 20,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "team_4" as any,
		_creationTime: Date.now() - 86400000 * 35,
		tournamentId: "tournament_1" as any,
		name: "Lions",
		description: "Power hitting team with strong pitchers",
		coachName: "Jennifer Martinez",
		coachEmail: "j.martinez@lions.com",
		coachPhone: "555-0126",
		city: "Westfield",
		homeField: "Lions Park",
		organization: "Westfield Youth Sports",
		teamAgeGroup: "U14",
		status: "active",
		captainPlayerId: "player_18" as any,
		createdAt: Date.now() - 86400000 * 35,
		updatedAt: Date.now() - 86400000 * 3,
	},
	{
		_id: "team_5" as any,
		_creationTime: Date.now() - 86400000 * 28,
		tournamentId: "tournament_1" as any,
		name: "Tigers",
		description: "Balanced team with solid all-around skills",
		coachName: "Robert Kim",
		coachEmail: "r.kim@tigers.com",
		coachPhone: "555-0127",
		city: "Northwood",
		homeField: "Tiger Stadium",
		organization: "Northwood Baseball Academy",
		teamAgeGroup: "U14",
		status: "active",
		captainPlayerId: "player_23" as any,
		createdAt: Date.now() - 86400000 * 28,
		updatedAt: Date.now() - 86400000 * 4,
	},
	{
		_id: "team_6" as any,
		_creationTime: Date.now() - 86400000 * 40,
		tournamentId: "tournament_1" as any,
		name: "Panthers",
		description: "Currently suspended for the season",
		coachName: "Amanda Wilson",
		coachEmail: "a.wilson@panthers.com",
		coachPhone: "555-0128",
		city: "Southgate",
		homeField: "Panthers Field",
		organization: "Southgate Sports League",
		teamAgeGroup: "U14",
		status: "suspended",
		captainPlayerId: undefined,
		createdAt: Date.now() - 86400000 * 40,
		updatedAt: Date.now() - 86400000 * 10,
	},
];

/**
 * Helper function to get a team by ID
 */
export function getMockTeamById(teamId: string) {
	return mockTeams.find((team) => team._id === teamId) || null;
}

/**
 * Helper function to get active teams only
 */
export function getActiveMockTeams() {
	return mockTeams.filter((team) => team.status === "active");
}
