/**
 * Mock Players Data
 *
 * This file contains realistic mock player data for development and testing.
 * Each player includes proper team references and realistic information.
 */

import type { Doc } from "../../../convex/_generated/dataModel";
import { mockTeams } from "./mockTeams";

/**
 * Mock player data that matches the Convex players schema
 *
 * Note: In real data, _id would be generated by Convex.
 * For mock data, we use string IDs for consistency.
 */
export const mockPlayers: Doc<"players">[] = [
	// Thunderbirds Players (team_1)
	{
		_id: "player_1" as any,
		_creationTime: Date.now() - 86400000 * 29,
		userId: undefined,
		teamId: "team_1" as any,
		firstName: "Ethan",
		lastName: "Mitchell",
		jerseyNumber: 12,
		email: "ethan.mitchell@email.com",
		phone: "555-1001",
		birthDate: Date.now() - 86400000 * 365 * 13, // 13 years old
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 29,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_2" as any,
		_creationTime: Date.now() - 86400000 * 28,
		userId: undefined,
		teamId: "team_1" as any,
		firstName: "Liam",
		lastName: "Thompson",
		jerseyNumber: 5,
		email: "liam.t@email.com",
		phone: "555-1002",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 28,
		updatedAt: Date.now() - 86400000 * 2,
	},
	{
		_id: "player_3" as any,
		_creationTime: Date.now() - 86400000 * 27,
		userId: undefined,
		teamId: "team_1" as any,
		firstName: "Noah",
		lastName: "Anderson",
		jerseyNumber: 23,
		email: "noah.a@email.com",
		phone: "555-1003",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: true,
		status: "active",
		createdAt: Date.now() - 86400000 * 27,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_4" as any,
		_creationTime: Date.now() - 86400000 * 26,
		userId: undefined,
		teamId: "team_1" as any,
		firstName: "Oliver",
		lastName: "Williams",
		jerseyNumber: 8,
		email: undefined,
		phone: "555-1004",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "injured",
		createdAt: Date.now() - 86400000 * 26,
		updatedAt: Date.now() - 86400000 * 3,
	},

	// Warriors Players (team_2)
	{
		_id: "player_5" as any,
		_creationTime: Date.now() - 86400000 * 24,
		userId: undefined,
		teamId: "team_2" as any,
		firstName: "Lucas",
		lastName: "Brown",
		jerseyNumber: 15,
		email: "lucas.b@email.com",
		phone: "555-2001",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 24,
		updatedAt: Date.now() - 86400000 * 2,
	},
	{
		_id: "player_6" as any,
		_creationTime: Date.now() - 86400000 * 23,
		userId: undefined,
		teamId: "team_2" as any,
		firstName: "Henry",
		lastName: "Davis",
		jerseyNumber: 7,
		email: "henry.d@email.com",
		phone: "555-2002",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 23,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_7" as any,
		_creationTime: Date.now() - 86400000 * 22,
		userId: undefined,
		teamId: "team_2" as any,
		firstName: "Alexander",
		lastName: "Miller",
		jerseyNumber: 33,
		email: "alex.m@email.com",
		phone: "555-2003",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: true,
		status: "active",
		createdAt: Date.now() - 86400000 * 22,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_8" as any,
		_creationTime: Date.now() - 86400000 * 21,
		userId: undefined,
		teamId: "team_2" as any,
		firstName: "Benjamin",
		lastName: "Wilson",
		jerseyNumber: 2,
		email: undefined,
		phone: undefined,
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "inactive",
		createdAt: Date.now() - 86400000 * 21,
		updatedAt: Date.now() - 86400000 * 7,
	},

	// Eagles Players (team_3)
	{
		_id: "player_9" as any,
		_creationTime: Date.now() - 86400000 * 19,
		userId: undefined,
		teamId: "team_3" as any,
		firstName: "Mason",
		lastName: "Taylor",
		jerseyNumber: 11,
		email: "mason.t@email.com",
		phone: "555-3001",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 19,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_10" as any,
		_creationTime: Date.now() - 86400000 * 18,
		userId: undefined,
		teamId: "team_3" as any,
		firstName: "William",
		lastName: "Anderson",
		jerseyNumber: 44,
		email: "will.a@email.com",
		phone: "555-3002",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 18,
		updatedAt: Date.now() - 86400000 * 2,
	},
	{
		_id: "player_11" as any,
		_creationTime: Date.now() - 86400000 * 17,
		userId: undefined,
		teamId: "team_3" as any,
		firstName: "James",
		lastName: "Thomas",
		jerseyNumber: 9,
		email: "james.t@email.com",
		phone: "555-3003",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 17,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_12" as any,
		_creationTime: Date.now() - 86400000 * 16,
		userId: undefined,
		teamId: "team_3" as any,
		firstName: "Daniel",
		lastName: "Jackson",
		jerseyNumber: 16,
		email: "dan.j@email.com",
		phone: "555-3004",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: true,
		status: "active",
		createdAt: Date.now() - 86400000 * 16,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_13" as any,
		_creationTime: Date.now() - 86400000 * 15,
		userId: undefined,
		teamId: "team_3" as any,
		firstName: "Michael",
		lastName: "White",
		jerseyNumber: 27,
		email: "mike.w@email.com",
		phone: "555-3005",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 15,
		updatedAt: Date.now() - 86400000 * 2,
	},

	// Lions Players (team_4)
	{
		_id: "player_14" as any,
		_creationTime: Date.now() - 86400000 * 34,
		userId: undefined,
		teamId: "team_4" as any,
		firstName: "Joseph",
		lastName: "Harris",
		jerseyNumber: 3,
		email: "joe.h@email.com",
		phone: "555-4001",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 34,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_15" as any,
		_creationTime: Date.now() - 86400000 * 33,
		userId: undefined,
		teamId: "team_4" as any,
		firstName: "David",
		lastName: "Martin",
		jerseyNumber: 19,
		email: undefined,
		phone: "555-4002",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 33,
		updatedAt: Date.now() - 86400000 * 3,
	},
	{
		_id: "player_16" as any,
		_creationTime: Date.now() - 86400000 * 32,
		userId: undefined,
		teamId: "team_4" as any,
		firstName: "Samuel",
		lastName: "Garcia",
		jerseyNumber: 31,
		email: "sam.g@email.com",
		phone: "555-4003",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "injured",
		createdAt: Date.now() - 86400000 * 32,
		updatedAt: Date.now() - 86400000 * 5,
	},
	{
		_id: "player_17" as any,
		_creationTime: Date.now() - 86400000 * 31,
		userId: undefined,
		teamId: "team_4" as any,
		firstName: "Carter",
		lastName: "Rodriguez",
		jerseyNumber: 6,
		email: "carter.r@email.com",
		phone: "555-4004",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 31,
		updatedAt: Date.now() - 86400000 * 2,
	},
	{
		_id: "player_18" as any,
		_creationTime: Date.now() - 86400000 * 30,
		userId: undefined,
		teamId: "team_4" as any,
		firstName: "Wyatt",
		lastName: "Lopez",
		jerseyNumber: 42,
		email: "wyatt.l@email.com",
		phone: "555-4005",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: true,
		status: "active",
		createdAt: Date.now() - 86400000 * 30,
		updatedAt: Date.now() - 86400000 * 1,
	},

	// Tigers Players (team_5)
	{
		_id: "player_19" as any,
		_creationTime: Date.now() - 86400000 * 27,
		userId: undefined,
		teamId: "team_5" as any,
		firstName: "Owen",
		lastName: "Gonzalez",
		jerseyNumber: 14,
		email: "owen.g@email.com",
		phone: "555-5001",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 27,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_20" as any,
		_creationTime: Date.now() - 86400000 * 26,
		userId: undefined,
		teamId: "team_5" as any,
		firstName: "Gabriel",
		lastName: "Perez",
		jerseyNumber: 10,
		email: "gabe.p@email.com",
		phone: "555-5002",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 26,
		updatedAt: Date.now() - 86400000 * 2,
	},
	{
		_id: "player_21" as any,
		_creationTime: Date.now() - 86400000 * 25,
		userId: undefined,
		teamId: "team_5" as any,
		firstName: "Julian",
		lastName: "Sanchez",
		jerseyNumber: 22,
		email: "julian.s@email.com",
		phone: "555-5003",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "active",
		createdAt: Date.now() - 86400000 * 25,
		updatedAt: Date.now() - 86400000 * 1,
	},
	{
		_id: "player_22" as any,
		_creationTime: Date.now() - 86400000 * 24,
		userId: undefined,
		teamId: "team_5" as any,
		firstName: "Levi",
		lastName: "Ramirez",
		jerseyNumber: 35,
		email: undefined,
		phone: "555-5004",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "inactive",
		createdAt: Date.now() - 86400000 * 24,
		updatedAt: Date.now() - 86400000 * 6,
	},
	{
		_id: "player_23" as any,
		_creationTime: Date.now() - 86400000 * 23,
		userId: undefined,
		teamId: "team_5" as any,
		firstName: "Isaac",
		lastName: "Cruz",
		jerseyNumber: 1,
		email: "isaac.c@email.com",
		phone: "555-5005",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: true,
		status: "active",
		createdAt: Date.now() - 86400000 * 23,
		updatedAt: Date.now() - 86400000 * 1,
	},

	// Panthers Players (team_6 - suspended team)
	{
		_id: "player_24" as any,
		_creationTime: Date.now() - 86400000 * 39,
		userId: undefined,
		teamId: "team_6" as any,
		firstName: "Jack",
		lastName: " Torres",
		jerseyNumber: 18,
		email: "jack.t@email.com",
		phone: "555-6001",
		birthDate: Date.now() - 86400000 * 365 * 13,
		isCaptain: false,
		status: "inactive",
		createdAt: Date.now() - 86400000 * 39,
		updatedAt: Date.now() - 86400000 * 10,
	},
	{
		_id: "player_25" as any,
		_creationTime: Date.now() - 86400000 * 38,
		userId: undefined,
		teamId: "team_6" as any,
		firstName: "Luke",
		lastName: " Flores",
		jerseyNumber: 28,
		email: "luke.f@email.com",
		phone: "555-6002",
		birthDate: Date.now() - 86400000 * 365 * 14,
		isCaptain: false,
		status: "inactive",
		createdAt: Date.now() - 86400000 * 38,
		updatedAt: Date.now() - 86400000 * 10,
	},
];

/**
 * Helper function to get players with their team data
 * This simulates the join operation that Convex queries would do
 */
export function getMockPlayersWithTeams() {
	return mockPlayers.map((player) => {
		const team = mockTeams.find((t) => t._id === player.teamId);
		return {
			...player,
			team: team || null,
		};
	});
}

/**
 * Helper function to get a player by ID with team data
 */
export function getMockPlayerById(playerId: string) {
	const player = mockPlayers.find((p) => p._id === playerId);
	if (!player) return null;

	const team = mockTeams.find((t) => t._id === player.teamId);
	return {
		...player,
		team: team || null,
	};
}

/**
 * Helper function to search players by text
 */
export function searchMockPlayers(query: string) {
	const searchTerm = query.toLowerCase();
	const playersWithTeams = getMockPlayersWithTeams();

	return playersWithTeams.filter(
		(player) =>
			player.firstName.toLowerCase().includes(searchTerm) ||
			player.lastName.toLowerCase().includes(searchTerm) ||
			(player.email && player.email.toLowerCase().includes(searchTerm)),
	);
}

/**
 * Helper function to get active players only
 */
export function getActiveMockPlayers() {
	return mockPlayers.filter((player) => player.status === "active");
}
