/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentspageIndexRouteImport } from './routes/tournamentspage/index'
import { Route as TeamspageIndexRouteImport } from './routes/teamspage/index'
import { Route as PlayerspageIndexRouteImport } from './routes/playerspage/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'

const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentspageIndexRoute = TournamentspageIndexRouteImport.update({
  id: '/tournamentspage/',
  path: '/tournamentspage/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamspageIndexRoute = TeamspageIndexRouteImport.update({
  id: '/teamspage/',
  path: '/teamspage/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerspageIndexRoute = PlayerspageIndexRouteImport.update({
  id: '/playerspage/',
  path: '/playerspage/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/playerspage': typeof PlayerspageIndexRoute
  '/teamspage': typeof TeamspageIndexRoute
  '/tournamentspage': typeof TournamentspageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/dashboard': typeof DashboardIndexRoute
  '/playerspage': typeof PlayerspageIndexRoute
  '/teamspage': typeof TeamspageIndexRoute
  '/tournamentspage': typeof TournamentspageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/playerspage/': typeof PlayerspageIndexRoute
  '/teamspage/': typeof TeamspageIndexRoute
  '/tournamentspage/': typeof TournamentspageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/dashboard'
    | '/playerspage'
    | '/teamspage'
    | '/tournamentspage'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/dashboard'
    | '/playerspage'
    | '/teamspage'
    | '/tournamentspage'
  id:
    | '__root__'
    | '/'
    | '/mcp'
    | '/dashboard/'
    | '/playerspage/'
    | '/teamspage/'
    | '/tournamentspage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  McpRoute: typeof McpRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  PlayerspageIndexRoute: typeof PlayerspageIndexRoute
  TeamspageIndexRoute: typeof TeamspageIndexRoute
  TournamentspageIndexRoute: typeof TournamentspageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournamentspage/': {
      id: '/tournamentspage/'
      path: '/tournamentspage'
      fullPath: '/tournamentspage'
      preLoaderRoute: typeof TournamentspageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teamspage/': {
      id: '/teamspage/'
      path: '/teamspage'
      fullPath: '/teamspage'
      preLoaderRoute: typeof TeamspageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playerspage/': {
      id: '/playerspage/'
      path: '/playerspage'
      fullPath: '/playerspage'
      preLoaderRoute: typeof PlayerspageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  McpRoute: McpRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  PlayerspageIndexRoute: PlayerspageIndexRoute,
  TeamspageIndexRoute: TeamspageIndexRoute,
  TournamentspageIndexRoute: TournamentspageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
